### ISSUE TITLE
Support automatic scaling of gateway deployment

### ISSUE THREAD

**Issue by rakkhin** [TykTechnologies/tyk-charts#115]
Currently Tyk Gateway deployed with `tyk-gateway` chart doesn't support automatic scaling with HPA k8s resource. While it is possible to manually create HPA it is not recommended, as it would lead to a potentially dangerous situation in upgrade/redeployment scenario:

1. Manually created HPA monitors tyk-gateway Deployment and based on given utilization parameters decides to scale it to 8 pods
2. All 8 pods are ready and processing requests, load conditions persist, keeping HPA scaling request at 8 pods
3. Team deploys new version of tyk-gateway with helm chart without support for HPA (so statically set `replicaCount` to some value, most likely lower than 8)
4. Deployment is scaled down to a value set in `replicaCount` helm value
5. Before HPA reacts service overloads.

To avoid situations like that there should be a HPA resource defined in helm chart, deployed conditionally if autoscaling configuration is desired by the Team.

**Comment by caroltyk** [comment]
Issue has been fixed. Thanks for raising this @rakkhin !
