### ISSUE TITLE
[TT-10178] Include README.md for Enterprise Developer Portal

### ISSUE THREAD

**Issue by oluwaseyeayinla** [TykTechnologies/tyk-charts#124]
Enterprise developer portal helm documentation is missing. Can a readme doc be added? 

Linked from community post https://community.tyk.io/t/tyk-enterprise-developer-portal-github-helm-documentation-missing/6729

**Comment by caroltyk** [comment]
Hi @oluwaseyeayinla , please check the docs here.
https://github.com/TykTechnologies/tyk-charts/tree/main/components/tyk-dev-portal

Further documentations can be found at
1. https://tyk.io/docs/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm/
2. https://tyk.io/docs/deployment-and-operations/tyk-self-managed/deployment-lifecycle/installations/kubernetes/tyk-helm-tyk-stack/
