### ISSUE TITLE
Impossible to use entrypoint script

### ISSUE THREAD

**Issue by jakub-bochenski** [TykTechnologies/tyk-charts#128]
Entrypoint scripts are a common pattern in Docker images and a best practice (c.f. https://docs.docker.com/develop/develop-images/instructions/#entrypoint , https://www.camptocamp.com/en/news-events/flexible-docker-entrypoints-scripts )

It's impossible to use one with the provided helm charts because they override the image entrypoint.

The override is effectively the same as default entrypoint for the docker image, so it's not doing anything useful

```
        command: ["/opt/tyk-gateway/tyk"]
        workingDir: /opt/tyk-gateway
```

```
            "Cmd": [
                "--conf=/opt/tyk-gateway/tyk.conf"
            ],
            "WorkingDir": "/opt/tyk-gateway/",
            "Entrypoint": [
                "/opt/tyk-gateway/tyk"
            ],

```
(the --conf is effectively the same as not specifying it since it reads tyk.conf from tyk home)

**Comment by caroltyk** [comment]
Issue fixed, thank you @jakub-bochenski !
