### ISSUE TITLE
Harmonise readmes

### ISSUE THREAD

**Issue by cattired** [TykTechnologies/tyk-charts#138]
Both tyk-oss and tyk-mdcb-data-plane contain a section "[Gateway Configurations](https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-mdcb-data-plane#gateway-configurations)". I suggest to move it to tyk-gateway Readme and leave a reference to it in tyk-oss and tyk-mdcb-data-plane. Would be more common sense and easier to maintain imho.

**Comment by caroltyk** [comment]
Hi @cattired , we are investigating automate the synchronisation of docs between all charts. Any ideas would be welcome!

**Comment by cattired** [comment]
Hey, I'd love to do what I mentioned above, it would at least remove some redundancy but I've been waiting for my original PR to be merged since months: https://github.com/TykTechnologies/tyk-charts/pull/135 Any chance to get any progress on it?

**Comment by caroltyk** [comment]
Hi @cattired , we will be incorporating #135 in coming release, which should be ready in Feb / Mar.

**Comment by caroltyk** [comment]
@cattired we have harmonised our docs in our official website. Please check out [Docs site](https://tyk.io/docs/product-stack/tyk-charts/overview/).
