### ISSUE TITLE
There should be an option to deploy a separate ingress for control api when control in enabled

### ISSUE THREAD

**Issue by utkarsh079** [TykTechnologies/tyk-charts#171]
In tyk-headless, when you `control.enabled: true`, it creates a new service for control api but there is no template or option to create a separate ingress. In our environment we use two sets of ingresses, an internal and public. In case of control api, it makes sense to add an internal ingress to connect to control api.

**Comment by zalbiraw** [comment]
Hi @utkarsh079 I moved this issue to our new charts project. You're more than welcome to submit a PR here. It should be a pretty easy addition.

**Comment by caroltyk** [comment]
PR #135

**Comment by caroltyk** [comment]
Duplicate with #132
