### ISSUE TITLE
Changing the APISecret value does not trigger redeployment

### ISSUE THREAD

**Issue by djablonski-moia** [TykTechnologies/tyk-charts#258]
When updating thew value of the APISecret, the value is changed in the secret, but the deployment does not know of this change, and therefore continues to run with the old value.

To mitigate this, the typical Helm trick of using a checksum as an annotation should be used, at least when `global.secrets.useSecretName` is not set (won't work in that case).

**Comment by buraksekili** [comment]
Thank you @djablonski-moia for your contribution. Now, your contribution is merged and it will be part of the future release. Again, thank you for the suggestion and great contribution!
