### ISSUE TITLE
TYK-OSS chart license

### ISSUE THREAD

**Issue by KilianHaag** [TykTechnologies/tyk-charts#304]
I noticed the lack of an explicit LICENSE in this repository, while it is listed under the components https://tyk.io/docs/tyk-stack/#tyk-open-source and https://tyk.io/docs/apim/open-source/#tyk-open-source with an explicit mention of MPL2.0.
In comparison, the tyk gateway repository https://github.com/TykTechnologies/tyk explicitly has the MPL2.0 set.

Therefore, I would like to confirm, if the (implicit) application of the MPL2.0 is in fact your intent for this chart repository including the oss-chart. If I understand that correctly, it would require me to publish any changes to the chart, as there are no binaries of a helm chart.

No matter the outcome I'm looking forward to a clarification.

**Comment by buger** [comment]
You are correct with your assumption, and indeed missing license is an issue. I just added it. 
Thanks!
