### ISSUE TITLE
Cannot use tyk-stack chart with secrets provided by Secrets Store CSI Driver

### ISSUE THREAD

**Issue by nbentfeld** [TykTechnologies/tyk-charts#314]
We use the Azure Key Vault provider for Secrets Store CSI Driver in an Azure Kubernetes Service (AKS) cluster. The bootstrap component chart requires the dashboard license key to be present in a secret. With our setup, we have to mount the secret before it is available.
We can mount the secret in the dashboard, gateway and pump pods, but not in the bootstrap-pre-install job.
That job is preventing all other pods to be deployed (because of the helm hook), which means we cannot deploy the Tyk stack at all.
There are two options to make the chart work for us:
- add an option to disable the bootstrap jobs completely
- add an option to mount secrets in the bootstrap jobs

**Comment by buraksekili** [comment]
Thank you @nbentfeld, I'll raise internal ticket for this and review your PR when I can.
