### ISSUE TITLE
Unable to define pod annotations in tyk-gateway Helm Chart

### ISSUE THREAD

**Issue by alecor191** [TykTechnologies/tyk-charts#51]
I have the need to apply annotations to the Tyk Gateway pod. In the Helm chart's `values.yaml` file I can only see the ability to add annotations to the service, control, ingress, pump. But I would need to add annotations to the Gateway pod.

Essentially I'm looking for a parameter similar to `podAnnotations` in the [Kong Helm Chart](https://github.com/Kong/charts/blob/main/charts/kong/README.md) or [NGINX Ingress Helm Chart](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx).

Is there a way to define pod annotations when installing the Tyk Gateway via Helm chart?

**Comment by buraksekili** [comment]
hi @alecor191, thanks for bringing this up. this is indeed a missing piece at the moment. 
we will be working on this and hope to release it in the next release.

**Comment by alecor191** [comment]
Thanks a lot @buraksekili for considering this for the next release!

**Comment by buraksekili** [comment]
@alecor191 thank you again for this feature request :) We merged a PR and it'll be available for the next release. Thanks again
