### ISSUE TITLE
Tyk-oss service issue with the Helm chart.

### ISSUE THREAD

**Issue by leroyabiguime** [TykTechnologies/tyk-charts#57]
Tyk-pump-service is not created automatically when we enable it. There is a need to do it manually by exposing the deployment via the cmd (kubectl expose ...).

I think it should be nice to have it.
I am using this tyk version https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-oss

**Comment by caroltyk** [comment]
Thank you @leroyabiguime for your comment. We are working on adding a service for pump in the next release.

**Comment by buraksekili** [comment]
hi @leroyabiguime, #65 (Tyk Pump Service) is merged now and it'll be available in the next release. Thanks for the feature request.
